import {
  Award,
  BadgeCheck,
  Banknote,
  BookOpen,
  BookOpenCheck,
  Brain,
  Briefcase,
  Building2,
  Calendar,
  CalendarCheck,
  ChartNoAxesCombined,
  CircleCheck,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Compass,
  FileCheck2,
  FileText,
  Flag,
  GraduationCap,
  Handshake,
  HeartPulse,
  House,
  Landmark,
  Languages,
  Lightbulb,
  Mail,
  MapPin,
  MessageCircle,
  Mic,
  Phone,
  Plane,
  Rocket,
  Route,
  School,
  Search,
  ShieldCheck,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Trophy,
  UserCheck,
  Users,
  Wallet,
  type LucideIcon,
} from 'lucide-react';

/** Icon registry so content data can reference icons by name. */
export const icons = {
  award: Award,
  badge: BadgeCheck,
  bank: Banknote,
  book: BookOpen,
  bookCheck: BookOpenCheck,
  brain: Brain,
  briefcase: Briefcase,
  building: Building2,
  calendar: Calendar,
  calendarCheck: CalendarCheck,
  chart: ChartNoAxesCombined,
  check: CircleCheck,
  clipboard: ClipboardCheck,
  clipboardList: ClipboardList,
  clock: Clock,
  compass: Compass,
  fileCheck: FileCheck2,
  file: FileText,
  flag: Flag,
  graduation: GraduationCap,
  handshake: Handshake,
  health: HeartPulse,
  home: House,
  landmark: Landmark,
  languages: Languages,
  idea: Lightbulb,
  mail: Mail,
  pin: MapPin,
  chat: MessageCircle,
  mic: Mic,
  phone: Phone,
  plane: Plane,
  rocket: Rocket,
  route: Route,
  school: School,
  search: Search,
  shield: ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  trend: TrendingUp,
  trophy: Trophy,
  userCheck: UserCheck,
  users: Users,
  wallet: Wallet,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
